# Generated by Django 2.2.4 on 2019-12-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('city', models.CharField(choices=[('JAKARTA', 'Jakarta'), ('BANDUNG', 'Bandung'), ('SURABAYA', 'Surabaya'), ('SEMARANG', 'Semarang'), ('MEDAN', 'Medan')], max_length=8)),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('trailer', models.URLField(blank=True)),
            ],
        ),
    ]
